version: '3.8'

services:
  foodcart-dev:
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_API_URL=https://forkify-api.herokuapp.com/api/v2
      - FAST_REFRESH=true
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start
